//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntityPhone
    {
        public int BusinessEntityID { get; set; }
        public int PhoneID { get; set; }
        public int PhoneNumberTypeID { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual EntityPhone EntityPhone { get; set; }
        public virtual PhoneNumberType PhoneNumberType { get; set; }
    }
}
