//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCountry
    {
        public string GlobalID { get; set; }
        public string GlobalName { get; set; }
        public string Image { get; set; }
    }
}
