//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalValue
    {
        public int ControlID { get; set; }
        public string ControlName { get; set; }
        public string Vn { get; set; }
        public string Eng { get; set; }
        public string Description { get; set; }
    }
}
