//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantPermission
    {
        public int PermissionId { get; set; }
        public int BusinessEntityID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
